### ISSUE TITLE
Maps of Health: Gap between death and time zero

### ISSUE THREAD

**Issue by danqaurooni** [cns-iu/a2agc-dataset#134]
In all three Maps of Health, there is a visible but variable gap in many of the rows between the time of death and the zero axis. The gap changes from one map to another and depending on how you sort the data. Screenshot below:

<img width="1385" alt="Screenshot 2023-05-03 at 13 12 28" src="https://user-images.githubusercontent.com/8041711/235990712-5636483b-b9fc-4d46-a6da-f6a3c3ec7272.png">

**Comment by edlu77** [comment]
@danqaurooni The final recorded event often comes before the time of death, so these gaps are expected.
